name: "Native: Mac"

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  native_debug:
    runs-on: macos-latest
    env:
      VCPKG_FEATURE_FLAGS: manifests,binarycaching
    steps:
      - uses: actions/checkout@v2
      - run: brew install cmake
      - name: "Setup Metal-cpp"
        run: |
          pwsh setup-metal-cpp.ps1
      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: "/usr/local/share/vcpkg" # todo: use $VCPKG_INSTALLATION_ROOT
          vcpkgGitCommitId: dafff8267e0685baa86140e5a5dcf4d9d7383592
          vcpkgJsonGlob: "${{ github.workspace }}/vcpkg.json"
          runVcpkgInstall: true
      - uses: lukka/run-cmake@v10
        with:
          configurePreset: "x64-osx"
          buildPreset: "x64-osx-debug"
          testPreset: "x64-osx-debug"
