name: "Native: Mac"

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build_debug:
    runs-on: macos-latest
    env:
      VCPKG_FEATURE_FLAGS: manifests,binarycaching
    steps:
      - uses: actions/checkout@v2
      - run: brew install swift-protobuf
      - uses: lukka/run-vcpkg@v7.3
        with:
          vcpkgArguments: "protobuf:x64-osx protobuf:arm64-osx"
          vcpkgDirectory: "/usr/local/share/vcpkg" # todo: use $VCPKG_INSTALLATION_ROOT
          vcpkgTriplet: "x64-osx"
          vcpkgGitCommitId: e6dcc079c81161786eb7b052209a2047e79f2c6c
          cleanAfterBuild: true
      - uses: lukka/run-cmake@v3.4
        with:
          useVcpkgToolchainFile: true
          cmakeBuildType: "Debug"
          buildDirectory: "${{ github.workspace }}/build"
          buildWithCMake: true
          buildWithCMakeArgs: "--config Debug --target codegen sample"

  build_release:
    runs-on: macos-latest
    env:
      VCPKG_FEATURE_FLAGS: manifests,binarycaching
    steps:
      - uses: actions/checkout@v2
      - run: brew install swift-protobuf
      - uses: lukka/run-vcpkg@v7.3
        with:
          vcpkgArguments: "protobuf:x64-osx protobuf:arm64-osx"
          vcpkgDirectory: "/usr/local/share/vcpkg" # todo: use $VCPKG_INSTALLATION_ROOT
          vcpkgTriplet: "x64-osx"
          vcpkgGitCommitId: e6dcc079c81161786eb7b052209a2047e79f2c6c
          cleanAfterBuild: true
      - uses: lukka/run-cmake@v3.4
        with:
          useVcpkgToolchainFile: true
          cmakeBuildType: "Release"
          buildDirectory: "${{ github.workspace }}/build"
          buildWithCMake: true
          buildWithCMakeArgs: "--config Release --target codegen sample"
