name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: run-vcpkg
      uses: lukka/run-vcpkg@v7.3
      with:
        vcpkgArguments: "protobuf protobuf:x64-osx"
        vcpkgDirectory: "/usr/local/share/vcpkg" # todo: use $VCPKG_INSTALLATION_ROOT
        vcpkgTriplet: "arm64-ios"
        vcpkgGitCommitId: e6dcc079c81161786eb7b052209a2047e79f2c6c
        cleanAfterBuild: true
    - name: run-cmake
      uses: lukka/run-cmake@v3.4
      with:
        cmakeGenerator: "Xcode"
        buildDirectory: "build"
        buildWithCMake: true
        buildWithCMakeArgs: "--clean-first --info --target codegen"        
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
