name: "Swift"

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  swiftpm:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v1.25.0
        with:
          swift-version: "5.9.0"
      - uses: ConorMacBride/install-package@v1.1.0
        with:
          brew: swiftlint
      - name: "Setup Metal-cpp"
        run: |
          ./setup-metal-cpp.ps1
        shell: pwsh
      - name: "Swift Build(Debug)"
        run: swift build --configuration debug # --verbose --target ...
      - name: "Swift Build(Release)"
        run: swift build --configuration release
      - name: "Swift Test"
        run: swift test --verbose --enable-code-coverage
      - name: "Swift Lint"
        run: swiftlint lint --output docs/lint.md --reporter markdown # --autocorrect
