#
# References
#  - https://github.com/lukka/CppBuildTasks-Validation/tree/master/.github/workflows
#
name: Swift

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: lukka/run-vcpkg@v7.3
      with:
        vcpkgArguments: "protobuf protobuf:arm64-ios"
        vcpkgDirectory: "/usr/local/share/vcpkg" # todo: use $VCPKG_INSTALLATION_ROOT
        vcpkgTriplet: "x64-osx"
        vcpkgGitCommitId: e6dcc079c81161786eb7b052209a2047e79f2c6c
        cleanAfterBuild: true
    - uses: lukka/run-cmake@v3.4
      with:
        cmakeAppendedArgs: "-G Xcode"
        useVcpkgToolchainFile: true
        buildDirectory: 'build'
        buildWithCMake: true
        buildWithCMakeArgs: "--clean-first --info --target codegen"        
    - name: "Swift Build"
      run: swift build -v
    - name: "Swift Test"
      run: swift test -v
    - name: "Swift Build"
      run: swift build -v --configuration release
